### ISSUE TITLE
dataloader program

### ISSUE THREAD

**Issue by zhahaha123** [prithuls/MV-SWIN-T#1]
Could you please provide your dataloader program?

**Comment by prithuls** [comment]
Thanks for your interest in our research. While we cannot provide data preprocessing and dataloader functions due to licensing restrictions, you can take inspiration from the following public repositories:
- https://github.com/CleonWong/Can-You-Find-The-Tumour
- https://github.com/hebamuhamed/Breast-Cancer-Detection/blob/main/Preprocessing/formatImages.ipynb
